#define MAX_APS 512
#define MAX_CANDIDATE_PASSWORDS 32
#define MAX_TIMEOUTS 1000 // 100 seconds

#define PRIO_SCAN  USER_TASK_PRIO_2
#define PRIO_CRACK USER_TASK_PRIO_0
#define PRIO_TEST  USER_TASK_PRIO_1
