#define SCAN_PRIO       USER_TASK_PRIO_0
#define CONNECT_PRIO    USER_TASK_PRIO_1
#define CRACK_PRIO      USER_TASK_PRIO_2

#define MAX_APS 512
#define MAX_CANDIDATE_PASSWORDS 32
#define MAX_TIMEOUTS 1000 // 100 seconds
